version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.3
    steps:
      - checkout
      - run:
          name: install specific Bundler
          command: |
            gem install bundler --version '2.3.4'
      - restore_cache:
          keys:
            - gemsv1-{{ checksum "Gemfile.lock" }}
            - gemsv1
      - run:
          name: Install deps
          command: |
            # ensure Gemfile.lock is not updated (via --frozen)
            bundle _2.3.4_ check || bundle _2.3.4_ install --frozen
      - run:
          name: Test deps
          command: |
            bundle _2.3.4_ exec cowsay
      - save_cache:
          key: gemsv1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
